name: Unit Tests

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          cache: "pip" # caching pip dependencies

      - name: Check out Prodigy
        uses: actions/checkout@v3
        with:
          repository: explosion/prodigy
          ref: v1.14.11
          path: ./prodigy
          ssh-key: ${{ secrets.GHA_PRODIGY_READ }}

      - name: Install prodigy
        run: |
          ls -la
          pip install ./prodigy
          python -m prodigy --help

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -e .
          pip install ruff pytest playwright
          playwright install
      
      - name: Run ruff
        if: always()
        shell: bash
        run: python -m ruff prodigy_ann tests

      # The e2e tests need to run after because the sbert download may mess things up.
      - name: Run pytest unit tests
        if: always()
        shell: bash
        run: python -m pytest tests -m "not e2e" -vvv
      
      - name: Run e2e tests
        if: always()
        shell: bash
        run: python -m pytest tests -m "e2e" -vvv